name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # 允许手动点击按钮触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      -       - name: Install Dependencies
        run: |
          sudo apt-get update
          # 增加了 autoconf-archive 和 libtool-bin，解决 autoreconf 错误
          sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf automake build-essential libssl-dev libffi-dev python3-dev libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev libharfbuzz-dev libfribidi-dev libxcb1-dev libsndfile1-dev cmake pkg-config autoconf-archive libtool-bin

      - name: Build APK with Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython
          
          # 关键步骤：初始化并运行 buildozer
          # GitHub 的 Ubuntu 环境网络很好，可以顺利下载 Android SDK
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-todo-apk
          path: bin/*.apk
